var menuJsonJs =
{

	"LGN" : {
		"GNB":false,			// 햄버거메뉴 사용여부
		"FREVE":false,			// 즐겨찾기에서 사용여부
		"LGN0001":{"menuTxt" : "로그인", "parentMenuCd" : null, "menuDept" : 1, "url" : "LGN/html/LGN0001.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0002":{"menuTxt" : "사용자인증", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0002.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0003":{"menuTxt" : "비밀번호변경", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0003.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0004":{"menuTxt" : "앱설치 권한동의팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0004.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0005":{"menuTxt" : "사용료 결제", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0005.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0006":{"menuTxt" : "개인정보 수집 및 이용안내", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0006.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"LGN0007":{"menuTxt" : "메시지 대량 발송 안내", "parentMenuCd" : null, "menuDept" : 2, "url" : "LGN/html/LGN0007.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"MAN" : {
		"GNB":false,
		"FREVE":false,
		"MAN0001":{"menuTxt" : "메인", "parentMenuCd" : null, "menuDept" : 1, "url" : "MAN/html/MAN0001.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0201":{"menuTxt" : "공지사항-텍스트팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0201.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0202":{"menuTxt" : "공지사항-이미지팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0203":{"menuTxt" : "공지사항-설문", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0203.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0301":{"menuTxt" : "알림", "parentMenuCd" : null, "menuDept" : 1, "url" : "MAN/html/MAN0301.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0302":{"menuTxt" : "알림상세페이지", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0401":{"menuTxt" : "일일 친절페스티벌", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0401.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0402":{"menuTxt" : "연간 친절페스티벌", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0402.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0501":{"menuTxt" : "설문조사", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0501.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0601":{"menuTxt" : "주간 근무 현황", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0601.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MAN0701":{"menuTxt" : "재해예방 동영상 테스트", "parentMenuCd" : null, "menuDept" : 2, "url" : "MAN/html/MAN0701.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"COM":{
		"GNB":false,
		"FREVE":false,
		"menuTxt" : "공통",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "",
		"COM0101":{"menuTxt" : "팝업 스캔", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0102":{"menuTxt" : "키패드", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0201":{"menuTxt" : "집배달 지도", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0201.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0202":{"menuTxt" : "팝업 지도", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0301":{"menuTxt" : "From 달력", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0301.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0302":{"menuTxt" : "FromTo 달력", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0401":{"menuTxt" : "직접입력 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0401.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0501":{"menuTxt" : "시간설정 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0501.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0601":{"menuTxt" : "인수자 선택", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0601.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0602":{"menuTxt" : "인수자 직접 입력", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0602.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0701":{"menuTxt" : "사유 등록", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0701.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0702":{"menuTxt" : "이미지 선택", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0702.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0801":{"menuTxt" : "주소 조회", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0801.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM0901":{"menuTxt" : "조회 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM0901.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM1001":{"menuTxt" : "금액 변경 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM1001.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM1101":{"menuTxt" : "약관 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM1101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"COM1201":{"menuTxt" : "SM APP 긴급사용", "parentMenuCd" : null, "menuDept" : 2, "url" : "COM/html/COM1201.html", "mainImgSrc" : "", "gnbImgClass" : ""}
	},
	"CLDL" : {
		"GNB":true,
		"FREVE":false,
		"menuTxt" : "집배달",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon dvl",
		"CLDL0101":{"menuTxt" : "집배달예정", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0101.html", "mainImgSrc" : "../../common/img/icon-fa5.png", "gnbImgClass" : ""},
		"CLDL0104":{"menuTxt" : "집하 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0104.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0106":{"menuTxt" : "배달 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0106.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0201":{"menuTxt" : "집배달출발", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0201.html", "mainImgSrc" : "../../common/img/icon-fa1.png", "gnbImgClass" : ""},
		"CLDL0202":{"menuTxt" : "집하출발 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0203":{"menuTxt" : "배달출발 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0203.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0204":{"menuTxt" : "기사메모", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0204.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0206":{"menuTxt" : "문자발송 문구 설정", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0206.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0301":{"menuTxt" : "집하완료", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0301.html", "mainImgSrc" : "../../common/img/icon-fa7.png", "gnbImgClass" : ""},
		"CLDL0305":{"menuTxt" : "집하완료 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0305.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0306":{"menuTxt" : "집하완료 스캔", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0306.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0307":{"menuTxt" : "보조송장 등록", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0307.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0401":{"menuTxt" : "배달완료", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0401.html", "mainImgSrc" : "../../common/img/icon-fa3.png", "gnbImgClass" : ""},
		"CLDL0402":{"menuTxt" : "인수자 선택", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0402.html", "mainImgSrc" : "", "gnbImgClass" : ""},//스캔 팝업에 넘길 인수자를 선택하는 팝업창
		"CLDL0403":{"menuTxt" : "인수자 직접입력", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0403.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0404":{"menuTxt" : "배달완료 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0404.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0405":{"menuTxt" : "서명 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0405.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0406":{"menuTxt" : "이미지 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0406.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0407":{"menuTxt" : "전화번호 변경 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0407.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0410":{"menuTxt" : "배달완료 사진촬영", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0410.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0601":{"menuTxt" : "사진전송", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0601.html", "mainImgSrc" : "../../common/img/icon-fa3.png", "gnbImgClass" : ""},
		// "CLDL0801":{"menuTxt" : "사진 일괄전송", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0801.html", "mainImgSrc" : "../../common/img/icon-fa3.png", "gnbImgClass" : ""},
		"CLDL0701":{"menuTxt" : "미배달사유 일괄등록", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0701.html", "mainImgSrc" : "../../common/img/icon-fa3.png", "gnbImgClass" : ""},
		"CLDL0801":{"menuTxt" : "지도", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0801.html", "mainImgSrc" : "../../common/img/icon-fa30.png", "gnbImgClass" : ""},
		"CLDL0802":{"menuTxt" : "지도운송장목록", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0802.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		// "CLDL0901":{"menuTxt" : "임시테스트", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0901.html", "mainImgSrc" : "../../common/img/icon-fa3.png", "gnbImgClass" : ""},
		"CLDL0501":{"menuTxt" : "집배달현황", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0501.html", "mainImgSrc" : "../../common/img/icon-fa20.png", "gnbImgClass" : ""},
		"CLDL0502":{"menuTxt" : "집하완료현황", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0502.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0503":{"menuTxt" : "배달완료현황", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/CLDL0503.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"BCGT0101":{"menuTxt" : "바코드생성리스트", "parentMenuCd" : null, "menuDept" : 2, "url" : "CLDL/html/BCGT0101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"CLDL0302":{"menuTxt" : "분류코드 검색", "parentMenuCd" : null, "menuDept" : 1, "url" : "CLDL/html/CLDL0302.html", "mainImgSrc" : "../../common/img/icon-fa7.png", "gnbImgClass" : ""}
	},
	"PID" :{
		"GNB":true,
		"FREVE":true,
		"menuTxt" : "집하예약출력",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon gath",
		"PID0101":{"menuTxt" : "접수/출력", "parentMenuCd" : null, "menuDept" : 1, "url" : "PID/html/PID0101.html", "mainImgSrc" : "../../common/img/icon-fa21.png", "gnbImgClass" : ""},
		"PID0102":{"menuTxt" : "상세화면", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PID0103":{"menuTxt" : "택배/반품접수", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0103.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PID0104":{"menuTxt" : "운임조회", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0104.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PID0105":{"menuTxt" : "거래처 조회 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0105.html", "mainImgSrc" : "../../common/img/icon-fa22.png", "gnbImgClass" : ""},
		"PID0201":{"menuTxt" : "B2B접수", "parentMenuCd" : null, "menuDept" : 1, "url" : "PID/html/PID0201.html", "mainImgSrc" : "../../common/img/icon-fa22.png", "gnbImgClass" : ""},
		"PID0202":{"menuTxt" : "매장 조회 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0202.html", "mainImgSrc" : "../../common/img/icon-fa22.png", "gnbImgClass" : ""},
		"PID0301":{"menuTxt" : "스마일픽업", "parentMenuCd" : null, "menuDept" : 1, "url" : "PID/html/PID0301.html", "mainImgSrc" : "../../common/img/icon-fa23.png", "gnbImgClass" : ""},
		"PID0302":{"menuTxt" : "스마일픽업", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PID0303":{"menuTxt" : "SM변경", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0303.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PID0401":{"menuTxt" : "바로반품", "parentMenuCd" : null, "menuDept" : 1, "url" : "PID/html/PID0401.html", "mainImgSrc" : "../../common/img/icon-fa9.png", "gnbImgClass" : ""},
		"PID0402":{"menuTxt" : "바로반품 상세정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "PID/html/PID0402.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		// 스캔 출력 개발 추 후 진행 예정
		"PID0501":{"menuTxt" : "FedEx 스캔출력", "parentMenuCd" : null, "menuDept" : 1, "url" : "PID/html/PID0501.html", "mainImgSrc" : "../../common/img/icon-fa27.png", "gnbImgClass" : ""}
	},
	"ARI":{
		"GNB":true,
		"FREVE":true,
		"menuTxt" : "도착발송",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon ari",
		"ARI0101":{"menuTxt" : "구간셔틀(도착)", "parentMenuCd" : null, "menuDept" : 1, "url" : "ARI/html/ARI0101.html", "mainImgSrc" : "../../common/img/icon-fa10.png", "gnbImgClass" : ""},
		"ARI0102":{"menuTxt" : "도착조회", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0103":{"menuTxt" : "연계일보번호입력", "parentMenuCd" : null, "menuDept" : 3, "url" : "ARI/html/ARI0103.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0104":{"menuTxt" : "연계일보조회팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0104.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0201":{"menuTxt" : "구간셔틀(발송)", "parentMenuCd" : null, "menuDept" : 1, "url" : "ARI/html/ARI0201.html", "mainImgSrc" : "../../common/img/icon-fa11.png", "gnbImgClass" : ""},
		"ARI0202":{"menuTxt" : "발송조회", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0301":{"menuTxt" : "소형적입", "parentMenuCd" : null, "menuDept" : 1, "url" : "ARI/html/ARI0301.html", "mainImgSrc" : "../../common/img/icon-fa24.png", "gnbImgClass" : ""},
		"ARI0302":{"menuTxt" : "소형적입조회", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0303":{"menuTxt" : "적입점소번호입력", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0303.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"ARI0304":{"menuTxt" : "운반장비번호입력", "parentMenuCd" : null, "menuDept" : 2, "url" : "ARI/html/ARI0304.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"FRE":{
		"GNB":true,
		"FREVE":true,
		"menuTxt" : "화물",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon fre",
		"FRE0101":{"menuTxt" : "화물신고", "parentMenuCd" : null, "menuDept" : 1, "url" : "FRE/html/FRE0101.html", "mainImgSrc" : "../../common/img/icon-fa12.png", "gnbImgClass" : ""},
		"FRE0102":{"menuTxt" : "사진등록", "parentMenuCd" : null, "menuDept" : 2, "url" : "FRE/html/FRE0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"FRE0201":{"menuTxt" : "화물사고 확인서", "parentMenuCd" : null, "menuDept" : 1, "url" : "FRE/html/FRE0201.html", "mainImgSrc" : "../../common/img/icon-fa13.png", "gnbImgClass" : ""},
		"FRE0301":{"menuTxt" : "화물추적", "parentMenuCd" : null, "menuDept" : 1, "url" : "FRE/html/FRE0301.html", "mainImgSrc" : "../../common/img/icon-fa14.png", "gnbImgClass" : ""},
		"FRE0302":{"menuTxt" : "화물정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "FRE/html/FRE0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"FRE0303":{"menuTxt" : "도착지변경", "parentMenuCd" : null, "menuDept" : 2, "url" : "FRE/html/FRE0303.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		//"FRE0401":{"menuTxt" : "화물사고 판정", "parentMenuCd" : null, "menuDept" : 1, "url" : "FRE/html/FRE0401.html", "mainImgSrc" : "../../common/img/icon-fa25.png", "gnbImgClass" : ""},
		"FRE0501":{"menuTxt" : "화물정보 키패드", "parentMenuCd" : null, "menuDept" : 2, "url" : "FRE/html/FRE0501.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"RES" : {
		"GNB":true,
		"FREVE":true,
		"menuTxt" : "실적조회",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon result",
		"RES0101":{"menuTxt" : "서비스실적", "parentMenuCd" : null, "menuDept" : 1, "url" : "RES/html/RES0101.html", "mainImgSrc" : "../../common/img/icon-fa15.png", "gnbImgClass" : ""},
		"RES0102":{"menuTxt" : "일일작업현황 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "RES/html/RES0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"RES0103":{"menuTxt" : "월별실적현황 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "RES/html/RES0103.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"RES0104":{"menuTxt" : "사진전송실적현황 팝업", "parentMenuCd" : null, "menuDept" : 2, "url" : "RES/html/RES0104.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	}
	,"FREVE" : {
		"GNB":true,
		"FREVE":false,
		"menuTxt" : "즐겨찾기",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon favo",
		"FREVE0101":{"menuTxt" : "즐겨찾기", "parentMenuCd" : null, "menuDept" : 1, "url" : "FREVE/html/FREVE0101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"SET":{
		"GNB":true,
		"FREVE":false,
		"menuTxt" : "설정",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon option",
		"SET0101":{"menuTxt" : "블루투스 설정", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0105":{"menuTxt" : "프린터 연결 모델", "parentMenuCd" : null, "menuDept" : 2, "url" : "SET/html/SET0105.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0201":{"menuTxt" : "문자발송 설정", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0201.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0202":{"menuTxt" : "문구 작성", "parentMenuCd" : null, "menuDept" : 2, "url" : "SET/html/SET0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0301":{"menuTxt" : "인수자 편집", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0301.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0302":{"menuTxt" : "미배달 사유 편집", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0302.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0304":{"menuTxt" : "미집하 사유 편집", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0304.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0401":{"menuTxt" : "자동문자발송 미동의/동의", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0401.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0501":{"menuTxt" : "집배달 시간대역 편집", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0501.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"SET0303":{"menuTxt" : "업무별 기능 설정", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0303.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		// "SET0601":{"menuTxt" : "기타 설정", "parentMenuCd" : null, "menuDept" : 1, "url" : "SET/html/SET0601.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	},
	"MYP":{
		"GNB":true,
		"FREVE":true,
		"menuTxt" : "MY PAGE",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon mypage",
		"MYP0101":{"menuTxt" : "마이페이지", "parentMenuCd" : null, "menuDept" : 1, "url" : "MYP/html/MYP0101.html", "mainImgSrc" : "../../common/img/icon-fa18.png", "gnbImgClass" : ""},
		"MYP0102":{"menuTxt" : "비밀번호 변경", "parentMenuCd" : null, "menuDept" : 2, "url" : "MYP/html/MYP0102.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"MYP0201":{"menuTxt" : "마일리지 교환신청", "parentMenuCd" : null, "menuDept" : 1, "url" : "MYP/html/MYP0201.html", "mainImgSrc" : "../../common/img/icon-fa18.png", "gnbImgClass" : ""},
		"MYP0301":{"menuTxt" : "마일리지 이력조회", "parentMenuCd" : null, "menuDept" : 1, "url" : "MYP/html/MYP0301.html", "mainImgSrc" : "../../common/img/icon-fa18.png", "gnbImgClass" : ""},
		"MYP0401":{"menuTxt" : "긴급사용 승인", "parentMenuCd" : null, "menuDept" : 1, "url" : "MYP/html/MYP0401.html", "mainImgSrc" : "../../common/img/icon-fa18.png", "gnbImgClass" : ""},
		"MYP0501":{"menuTxt" : "SM별 정산", "parentMenuCd" : null, "menuDept" : 1, "url" : "MYP/html/MYP0501.html", "mainImgSrc" : "../../common/img/icon-fa18.png", "gnbImgClass" : ""},
	},
	"PAY":{
		"GNB":true,
		"FREVE":false,
		"menuTxt" : "결제",
		"menuDept" : 0,
		"mainImgSrc" : "",
		"gnbImgClass" : "icon card",
		"PAY0101":{"menuTxt" : "결제현황/결제", "parentMenuCd" : null, "menuDept" : 1, "url" : "PAY/html/PAY0101.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PAY0201":{"menuTxt" : "결제내역/취소", "parentMenuCd" : null, "menuDept" : 1, "url" : "PAY/html/PAY0201.html", "mainImgSrc" : "", "gnbImgClass" : ""},
		"PAY0202":{"menuTxt" : "환불정보", "parentMenuCd" : null, "menuDept" : 2, "url" : "PAY/html/PAY0202.html", "mainImgSrc" : "", "gnbImgClass" : ""},
	}
};
